name: stabill
description: A Flutter project to serve a cloud based checkbook

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cloud_firestore: "^3.1.8"
  file_picker: ^4.4.0
  firebase_auth: "^3.3.7"
  firebase_core: "^1.12.0"
  firebase_messaging: "^11.1.0"
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.0.4
  flutter_speed_dial: ^5.0.0+1
  lint: ^1.8.2
  provider: ^6.0.2
  responsive_builder: ^0.4.2
  shared_preferences: ^2.0.13
  substring_highlight: ^1.0.33

dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#4caf50"
  image: assets/icon/logo_original_512.png
  color_dark: "#303030"
  fullscreen: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/icon/logo_android.png"
  adaptive_icon_background: "#4caf50"
  adaptive_icon_foreground: "assets/icon/logo_padded.png"
  image_path_ios: "assets/icon/logo_ios.png"

flutter:
  assets:
    - assets/icon/logo_only.png
  uses-material-design: true
