name: stabill
description: A Flutter project to serve a cloud based checkbook

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cloud_firestore: ^5.1.0
  csv: ^6.0.0
  file_picker: ^8.0.6
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  # firebase_messaging: "^11.1.0"
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.0.4
  flutter_speed_dial: ^7.0.0
  flutter_svg: ^2.0.10+1
  lint: ^2.3.0
  oktoast: ^3.1.5
  permission_handler: ^11.3.1
  provider: ^6.0.2
  responsive_builder: ^0.7.1
  shared_preferences: ^2.0.13
  substring_highlight: ^1.0.33

  intl: any
dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#4caf50"
  color_dark: "#303030"
  image: "assets/icon/logo_only.png"
  fullscreen: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/icon/logo_android.png"
  adaptive_icon_background: "#4caf50"
  adaptive_icon_foreground: "assets/icon/logo_padded.png"
  image_path_ios: "assets/icon/logo_ios.png"

flutter:
  assets:
    - assets/icon/logo_android.png
    - assets/icon/logo_only.png
    - assets/icon/logo_only.svg
  uses-material-design: true
