name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # Using stable channel for now, can also specify a version with: flutter-version: '3.10.0'

      - name: Install Flutter Dependencies
        working-directory: ./stabill
        run: flutter pub get

      - name: Build Flutter Web App
        working-directory: ./stabill
        run: flutter build web

      # Optional: Update the base href if needed (see section below)
      #- name: Update base href
      #  working-directory: ./stabill/build/web
      #  run: sed -i 's|<base href="/">|<base href="/Stabill/">|' index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true